"""Central configurable thresholds; OpenCV hue is 0–179 and Lab is 0–255."""
WORKING_MAX_DIMENSION=520; GAUSSIAN_KERNEL=(3,3)
MIN_FRUIT_COVERAGE=.012; MAX_FRUIT_COVERAGE=.82; MIN_COMPONENT_AREA_RATIO=.004
GREEN_H_MIN,GREEN_H_MAX=35,92; YELLOW_H_MIN,YELLOW_H_MAX=16,43; BROWN_H_MIN,BROWN_H_MAX=3,28
MIN_COLOR_SATURATION=38; MIN_COLOR_VALUE=55; GREEN_LAB_A_MAX=132; YELLOW_LAB_B_MIN=135; BROWN_LAB_A_MIN=126; BROWN_LAB_B_MIN=120
MIN_SPOT_AREA=18; SPOT_AREA_RATIO=.001; LOCAL_SPOT_CONTRAST=10
# Rule-based ripening-method thresholds.
NATURAL_SPOT_THRESHOLD=6.0
CHEMICAL_SPOT_THRESHOLD=2.5
NATURAL_SPOT_COUNT_THRESHOLD=8
CHEMICAL_SPOT_COUNT_THRESHOLD=3
HIGH_YELLOW_PERCENTAGE=85.0
NATURAL_COLOR_VARIATION_THRESHOLD=12.0
CHEMICAL_COLOR_VARIATION_THRESHOLD=8.0
NATURAL_TEXTURE_ENTROPY_THRESHOLD=5.5
CHEMICAL_TEXTURE_ENTROPY_THRESHOLD=4.5
NATURAL_GLCM_CONTRAST_THRESHOLD=1.0
CHEMICAL_GLCM_CONTRAST_THRESHOLD=0.5
NATURAL_TEXTURE_SCORE_THRESHOLD=0.8
CHEMICAL_GLCM_HOMOGENEITY_THRESHOLD=0.7
CHEMICAL_GLCM_ENERGY_THRESHOLD=0.65
NATURAL_MIN_EVIDENCE=3
CHEMICAL_MIN_EVIDENCE=4
LOW_QUALITY_BRIGHTNESS=45; LOW_QUALITY_CONTRAST=18; LOW_QUALITY_MIN_DIMENSION=100
# Banana validation thresholds
BANANA_DETECTION_THRESHOLD=0.60
YOLO_CONFIDENCE_THRESHOLD=0.50
IMAGE_QUALITY_BRIGHTNESS_MIN=30
IMAGE_QUALITY_CONTRAST_MIN=15
IMAGE_QUALITY_MIN_DIMENSION=80
